events {}   # Bloc de gestion des événements Nginx

http {      # Début de la configuration HTTP

  upstream wazuh {   # Groupe de serveurs pour Wazuh Dashboard
    server wazuh-dashboard:5601;   # Nom du conteneur + port interne
  }

  upstream keycloak {   # Groupe de serveurs pour Keycloak
    server keycloak:8080;   # Nom du conteneur + port interne
  }

  upstream liferay {   # Groupe de serveurs pour Liferay
    server liferay:8081;   # Nom du conteneur + port interne
  }

  server {

    listen 80;   # Nginx écoute sur HTTP

    location /wazuh {
      proxy_pass http://wazuh;   # Redirection vers Wazuh Dashboard
    }

    location /keycloak {
      proxy_pass http://keycloak;   # Redirection vers Keycloak
    }

    location /liferay {
      proxy_pass http://liferay;   # Redirection vers Liferay
    }

  }
}