FROM debian:12-slim

# =========================
# ENV VARIABLES
# =========================
ENV DEBIAN_FRONTEND=noninteractive
ENV OPENSEARCH_JAVA_OPTS="-Xms1g -Xmx1g"

# =========================
# BASE DEPENDENCIES
# =========================
RUN apt-get update && apt-get install -y \
    curl \
    bash \
    procps \
    gnupg \
    ca-certificates \
    openjdk-17-jre-headless \
    tar \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# =========================
# WAZUH REPOSITORY
# =========================
RUN curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH \
    | gpg --dearmor > /usr/share/keyrings/wazuh.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" \
    > /etc/apt/sources.list.d/wazuh.list && \
    apt-get update

# =========================
# INSTALL WAZUH INDEXER
# =========================
RUN apt-get install -y wazuh-indexer

# =========================
# DIRECTORIES
# =========================
RUN mkdir -p \
    /etc/wazuh-indexer/certs \
    /var/lib/wazuh-indexer \
    /var/log/wazuh-indexer

# =========================
# SECURITY CONFIG
# =========================
COPY security/ /usr/share/wazuh-indexer/opensearch-security/

# =========================
# OPENSEARCH CONFIG
# =========================
COPY config/opensearch.yml /etc/wazuh-indexer/opensearch.yml

# =========================
# ENTRYPOINT
# =========================
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh


# Données et logs
RUN chown -R wazuh-indexer:wazuh-indexer \
    /var/lib/wazuh-indexer \
    /var/log/wazuh-indexer \
    /etc/wazuh-indexer

# IMPORTANT
# opensearch-env lit ce fichier au démarrage
RUN chmod 644 /etc/default/wazuh-indexer

# Vérification pendant le build
RUN ls -l /etc/default/wazuh-indexer

# =========================
# USER
# =========================
USER wazuh-indexer

# =========================
# PORTS
# =========================
EXPOSE 9200 9300

# =========================
# START
# =========================
ENTRYPOINT ["/entrypoint.sh"]