nodes:
  indexer:
    - name: wazuh-indexer
      ip: "172.25.0.10"
      dns:
        - wazuh-indexer
        - localhost

  server:
    - name: wazuh-manager
      ip: "172.25.0.30"
      dns:
        - wazuh-manager
        - localhost

  dashboard:
    - name: wazuh-dashboard
      ip: "172.25.0.20"
      dns:
        - wazuh-dashboard
        - localhost