services:

  # =========================
  # INDEXER (OPENSEARCH)
  # =========================
  wazuh-indexer:
    # image: indexer_6:latest
    build: ./wazuh/wazuh-indexer
    container_name: wazuh-indexer
    restart: unless-stopped

    environment:
      - cluster.name=soc-cluster
      - node.name=wazuh-indexer
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g

    ulimits:
      memlock:
        soft: -1
        hard: -1

    ports:
      - "9200:9200"
      - "9600:9600"

    volumes:
      - ./wazuh/certs/indexer:/etc/wazuh-indexer/certs:ro
      - ./wazuh/wazuh-indexer/config/opensearch.yml:/etc/wazuh-indexer/opensearch.yml:ro

    networks:
      soc-network:
        ipv4_address: 172.25.0.10

    healthcheck:
      test: ["CMD-SHELL", "curl -k -u admin:admin https://wazuh-indexer:9200/_cluster/health | grep -q 'green\\|yellow'"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s


  # =========================
  # INIT INDEXER
  # =========================
  wazuh-init:
    image: indexer_6:latest
    container_name: wazuh-init
    depends_on:
      wazuh-indexer:
        condition: service_healthy

    networks:
      soc-network:
        ipv4_address: 172.25.0.50

    entrypoint: >
      sh -c "
      echo 'Indexer ready';
      sleep 10;
      curl -k -u admin:admin https://wazuh-indexer:9200/_cluster/health;
      echo 'Init done';
      "


  # =========================
  # DASHBOARD
  # =========================
  wazuh-dashboard:
    # image: soc_projet-wazuh-dashboard:latest
    build: ./wazuh/wazuh-dashboard
    container_name: wazuh-dashboard
    restart: unless-stopped

    ports:
      - "5601:5601"

    depends_on:
      wazuh-indexer:
        condition: service_healthy
      wazuh-init:
        condition: service_started

    volumes:
      - ./wazuh/certs/dashboard:/usr/share/wazuh-dashboard/certs:ro
      - ./wazuh/certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem:ro
      - ./wazuh/wazuh-dashboard/config/opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml:ro

    environment:
      - NODE_OPTIONS=--max-old-space-size=2048

    networks:
      soc-network:
        ipv4_address: 172.25.0.20


  # =========================
  # MANAGER + FILEBEAT
  # =========================
  wazuh-manager:
    # image: manager_new_04:latest
    build: ./wazuh/wazuh-manager
    container_name: wazuh-manager
    restart: unless-stopped
    privileged: true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cap_add:
      - ALL

    ports:
      - "1514:1514/udp"
      - "1515:1515/tcp"
      - "1516:55000/tcp"

    volumes:
      - ./wazuh/wazuh-manager/config/ossec.conf:/var/ossec/etc/ossec.conf
      - ./wazuh/wazuh-manager/data:/var/ossec/data
      - ./wazuh/wazuh-manager/logs:/var/ossec/logs
      - ./wazuh/wazuh-manager/rules/local_rules.xml:/var/ossec/etc/rules/local_rules.xml:ro
      - ./wazuh/certs/manager:/var/ossec/etc/ssl:ro
      - ./wazuh/wazuh-manager/config/filebeat.yml:/etc/filebeat/filebeat.yml:ro
      - ./wazuh/certs/root-ca.pem:/etc/filebeat/certs/root-ca.pem:ro
      - ./wazuh/wazuh-manager/scripts/ansible-trigger.sh:/var/ossec/active-response/bin/ansible-trigger.sh:ro
      - ./wazuh/wazuh-manager/config/authd.pass:/var/ossec/etc/authd.pass:ro
      - filebeat-data:/usr/share/filebeat/data

    depends_on:
      wazuh-indexer:
        condition: service_healthy

    networks:
      soc-network:
        ipv4_address: 172.25.0.30


  # ============================================
  # ANSIBLE (associer a un agent Wazuh installé)
  # ============================================
  ansible:
    # image: new_ansible:latest
    build: ./ansible
    container_name: ansible
    restart: unless-stopped
    volumes:
      - ./ansible/playbooks:/ansible/playbooks
      - ./ansible/inventory:/ansible/inventory
      - ./ansible/ansible.cfg:/etc/ansible/ansible.cfg:ro
      # - ./ansible/certificats:/ansible/var/
    working_dir: /ansible

    environment:
      - WAZUH_MANAGER_IP: ${WAZUH_MANAGER_IP}
      - WAZUH_AUTH_PORT: ${WAZUH_AUTH_PORT}
      - WAZUH_AGENT_PASSWORD: ${WAZUH_AGENT_PASSWORD}
    networks:
      soc-network:
        ipv4_address: 172.25.0.40


  # =========================
  # LIFERAY
  # =========================
  liferay:
    # image: liferay/portal:7.4.3.112-ga112
    build: ./liferay
    container_name: liferay
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - .liferay/data:/opt/liferay/data
      - .liferay/deploy:/opt/liferay/deploy
      - .liferay/config:/opt/liferay/config
    
    networks:
      soc-network:
        ipv4_address: 172.25.0.50

  # =========================
  # KEYCLOAK
  # =========================

  keycloak:
    # image: jboss/keycloak:latest
    build: ./keycloak
    container_name: keycloak
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    networks:
      soc-network:
        ipv4_address: 172.25.0.60

# =========================
# NETWORKS
# =========================
networks:
  soc-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24


volumes:
  filebeat-data: