name: wazuh-manager

# =========================
# INPUT WAZUH ALERTS
# =========================
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/ossec/logs/alerts/alerts.json

    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: log


# =========================
# OUTPUT : WAZUH INDEXER (OPENSEARCH)
# =========================
output.elasticsearch:
  hosts: ["https://wazuh-indexer:9200"]

  username: admin
  password: admin

  # IMPORTANT : compat OpenSearch / Wazuh
  allow_older_versions: true

  ssl.certificate_authorities: ["/etc/filebeat/certs/root-ca.pem"]
  ssl.verification_mode: certificate

  # index custom Wazuh
  index: "wazuh-alerts-%{+yyyy.MM.dd}"


# =========================
# CRITICAL FIX (évite _license / _xpack errors)
# =========================
setup.ilm.enabled: false
setup.ilm.check_exists: false
setup.ilm.overwrite: false

setup.xpack.enabled: false


# =========================
# TEMPLATE INDEX (WAZUH SAFE)
# =========================
setup.template.enabled: true
setup.template.name: "wazuh-alerts"
setup.template.pattern: "wazuh-alerts-*"

setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0


# =========================
# DISABLE MONITORING (IMPORTANT)
# =========================
monitoring.enabled: false
xpack.monitoring.enabled: false


# =========================
# LOGGING
# =========================
logging.level: info