# ==========================================
# Nom de l’instance Filebeat
# ==========================================
name: wazuh-manager   # Identifie ce Filebeat comme étant celui du Wazuh Manager

# ==========================================
# Entrée des logs (sources à collecter)
# ==========================================
filebeat.inputs:
  - type: log # Type de source : logs
    enabled: true  # active la collecte des logs  
    paths:
      - /var/ossec/logs/alerts/alerts.json # Chemin vers le fichier de logs Wazuh à collecter (format JSON)



# ==========================================
# Sortie des logs (destination)
# ==========================================
output.elasticsearch:
  hosts: ["https://wazuh-indexer:9200"]

  username: admin # identifiant pour se connecter à Elasticsearch (Wazuh Indexer)
  password: admin

  # IMPORTANT : compat OpenSearch / Wazuh
  allow_older_versions: true 

  ssl.certificate_authorities: ["/etc/filebeat/certs/root-ca.pem"] 
  ssl.verification_mode: certificate

  # index custom Wazuh
  index: "wazuh-alerts-%{+yyyy.MM.dd}" # Nom de l’index Elasticsearch où les logs Wazuh seront stockés, avec un suffixe de date pour la rotation des index


# =========================
# CRITICAL FIX (évite _license / _xpack errors)
# =========================
setup.ilm.enabled: false
setup.ilm.check_exists: false
setup.ilm.overwrite: false

setup.xpack.enabled: false


# =========================
# TEMPLATE INDEX (WAZUH SAFE)
# =========================
setup.template.enabled: true # 
setup.template.name: "wazuh-alerts" 
setup.template.pattern: "wazuh-alerts-*" 

setup.template.settings:
  index.number_of_shards: 1 
  index.number_of_replicas: 0 # 


# =========================
# DISABLE MONITORING (IMPORTANT)
# =========================
monitoring.enabled: false
xpack.monitoring.enabled: false


# =========================
# LOGGING
# =========================
logging.level: info
