FROM debian:12-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    tar \
    gnupg2 \
    wget \
    curl \
    && rm -rf /var/lib/apt/lists/*

#  opensearch-dashboards-2.11.0-linux-x64.tar.gz /tmp/
RUN wget https://artifacts.opensearch.org/releases/bundle/opensearch-dashboards/2.11.0/opensearch-dashboards-2.11.0-linux-x64.tar.gz \
    -O /tmp/opensearch-dashboards-2.11.0-linux-x64.tar.gz

RUN tar -xzf /tmp/opensearch-dashboards-2.11.0-linux-x64.tar.gz -C /usr/share/ \
    && mv /usr/share/opensearch-dashboards-2.11.0 /usr/share/opensearch-dashboards \
    && rm /tmp/opensearch-dashboards-2.11.0-linux-x64.tar.gz

EXPOSE 5601

CMD ["/usr/share/opensearch-dashboards/bin/opensearch-dashboards", "--allow-root"]