FROM debian:12-slim

ENV DEBIAN_FRONTEND=noninteractive

# ==========================================
# 1. Installation des dépendances système
# ==========================================
RUN apt-get update && apt-get install -y \
    curl \
    gnupg \
    apt-transport-https \
    lsb-release \
    ca-certificates \
    net-tools \
    vim \
    wget \
    && rm -rf /var/lib/apt/lists/*

# ==========================================
# 2. Ajout clé et dépôt Wazuh
# ==========================================
RUN curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -

RUN echo "deb https://packages.wazuh.com/4.x/apt/ stable main" \
    > /etc/apt/sources.list.d/wazuh.list

# ==========================================
# 3. Installation Wazuh Manager
# ==========================================
RUN apt-get update && apt-get install -y wazuh-manager

# ==========================================
# 4. Installation Filebeat
# ==========================================
RUN wget https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.13.4-amd64.deb \
    && dpkg -i filebeat-8.13.4-amd64.deb

# ==========================================
# 5. Ports utilisés
# ==========================================
EXPOSE 1514 1515 55000

# ================================
# 6. Démarrage du service
# ================================
CMD ["/var/ossec/bin/wazuh-control", "start"]