FROM debian:12-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV FILEBEAT_VERSION=7.10.2

# ==========================================
# 1. Installation des dépendances système
# ==========================================
RUN apt-get update && apt-get install -y \
    curl \
    gnupg \
    apt-transport-https \
    lsb-release \
    ca-certificates \
    net-tools \
    vim \
    wget \
    procps \
    && rm -rf /var/lib/apt/lists/*

# ==========================================
# 2. Ajout clé et dépôt Wazuh
# ==========================================
RUN curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --dearmor > /usr/share/keyrings/wazuh.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" > /etc/apt/sources.list.d/wazuh.list

# ==========================================
# 3. Installation Wazuh Manager
# ==========================================
RUN apt-get update && apt-get install -y wazuh-manager

# ==========================================
# 4. Installation Filebeat (version compatible)
# ==========================================
RUN curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-${FILEBEAT_VERSION}-amd64.deb && \
    dpkg -i filebeat-${FILEBEAT_VERSION}-amd64.deb && \
    rm filebeat-${FILEBEAT_VERSION}-amd64.deb

# ==========================================
# 7. Ports utilisés
# ==========================================
EXPOSE 1514 1515 55000

CMD ["/usr/bin/wazuh-manager"]