
[soc]

# Wazuh Manager
wazuh-manager ansible_host=172.25.0.20

# Wazuh Indexer
wazuh-indexer ansible_host=172.25.0.10

# Wazuh Dashboard
wazuh-dashboard ansible_host=172.25.0.30

# Keycloak
keycloak ansible_host=172.30.0.14

# Liferay
liferay ansible_host=172.30.0.15

# Ansible
ansible ansible_host=172.30.0.16

# Nginx
nginx ansible_host=172.30.0.17



# Variables communes aux hotes du groupe SOC

[soc:vars]

# Utilisateur distant
ansible_user=root

# Interpréteur Python utilisé
ansible_python_interpreter=/usr/bin/python3

# Désactivation vérification clé SSH
ansible_ssh_common_args='-o StrictHostKeyChecking=no'