FROM debian:12-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    openjdk-17-jdk wget unzip

RUN wget https://github.com/keycloak/keycloak/releases/download/25.0.0/keycloak-25.0.0.zip \
    && unzip keycloak-25.0.0.zip \
    && mv keycloak-25.0.0 /opt/keycloak

WORKDIR /opt/keycloak

EXPOSE 8080

CMD ["/opt/keycloak/bin/kc.sh", "start-dev"]
