events {}   # Bloc de gestion des événements et connexions Nginx

http {      # Début de la configuration des services HTTP

  upstream wazuh {     # Création d’un groupe de serveurs pour Wazuh Dashboard
    server wazuh-dashboard:5601;   # Adresse interne du conteneur Wazuh Dashboard
  }

  upstream keycloak {  # Création d’un groupe de serveurs pour Keycloak
    server keycloak:8080;   # Adresse interne du conteneur Keycloak
  }

  server {    # Début de la configuration du serveur web Nginx

    listen 80;   # Nginx écoute les requêtes entrantes sur le port HTTP 80

    location /wazuh {   # Route utilisée pour accéder au dashboard Wazuh
      proxy_pass http://wazuh;   # Redirection des requêtes vers Wazuh Dashboard
    }

    location /keycloak {   # Route utilisée pour accéder à Keycloak
      proxy_pass http://keycloak;   # Redirection des requêtes vers Keycloak
    }

  }
}
