FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    openjdk-11-jdk \
    wget \
    unzip \
    curl

# téléchargement Liferay
RUN wget https://github.com/liferay/liferay-portal/releases/download/7.4.3.88-ga88/liferay-ce-portal-tomcat-7.4.3.88-ga88.zip \
    && unzip liferay-ce-portal-tomcat-7.4.3.88-ga88.zip \
    && mv liferay-ce-portal-7.4.3.88-ga88 /opt/liferay

WORKDIR /opt/liferay

EXPOSE 8081

CMD ["catalina.sh", "run"]